---
- name: Setup Docker on Flask Weather Servers
  hosts: flask_servers
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      
    - name: Install Docker
      apt:
        name: docker.io
        state: present 
        
    - name: Pull Docker Image
      command: docker pull mostafahu/flask-weather-app
    
    - name: Run Docker Container
      command: docker run -d -P mostafahu/flask-weather-app

